stateDiagram-v2
    [*] --> T4_update_plugin_templates
    T4_update_plugin_templates : T4 Update plugin emit templates with workflow flag and convert work artifact calls
    T4_update_plugin_templates --> [*]
