version: 2

project_name: rp1

before:
  hooks:
    - cd cli && bun install

builds:
  - id: rp1
    builder: bun
    main: cli/src/main.ts
    binary: rp1
    targets:
      - darwin-arm64
      - darwin-x64
      - linux-arm64
      - linux-x64
      - windows-x64
    flags:
      - --compile
      - --minify

archives:
  - id: default
    formats:
      - binary
    name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}"

checksum:
  name_template: "checksums.txt"
  algorithm: sha256

release:
  github:
    owner: rp1-run
    name: rp1
  draft: false
  prerelease: auto
  name_template: "v{{ .Version }}"
  mode: keep-existing
  footer: |
    ## Installation

    ### macOS / Linux (Homebrew)
    ```bash
    brew install rp1-run/tap/rp1
    ```

    ### Windows (Scoop)
    ```bash
    scoop bucket add rp1 https://github.com/rp1-run/scoop-bucket
    scoop install rp1
    ```

    ### CI/CD (curl)
    ```bash
    curl -fsSL https://rp1.run/install.sh | sh
    ```

    ### Direct Download
    Download the appropriate binary for your platform from the assets below.

    ---
    **Full Changelog**: https://github.com/rp1-run/rp1/compare/{{ .PreviousTag }}...{{ .Tag }}

homebrew_casks:
  - name: rp1
    repository:
      owner: rp1-run
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    directory: Casks
    homepage: "https://rp1.run"
    description: "AI-assisted development workflows CLI"
    binaries:
      - rp1

scoops:
  - name: rp1
    repository:
      owner: rp1-run
      name: scoop-bucket
      token: "{{ .Env.SCOOP_BUCKET_TOKEN }}"
    directory: bucket
    homepage: "https://rp1.run"
    description: "AI-assisted development workflows CLI"
    license: MIT

changelog:
  use: github-native
