export {
	type ArcadeConfig,
	type CLIConfig,
	findRp1Root,
	loadArcadeConfig,
	parseArcadeArgs,
	resolveRp1Root,
} from "./config.js";
export {
	type DirectorySource,
	type ProjectRootSource,
	type ResolvedDirectorySet,
	resolveDirectorySet,
} from "./directory-resolution.js";

export {
	backupError,
	type CLIError,
	type CLIErrorWithExit,
	configError,
	ExitCode,
	formatError,
	generationError,
	getExitCode,
	installError,
	notFoundError,
	// Build error factories
	parseError,
	portInUseError,
	// Install error factories
	prerequisiteError,
	runtimeError,
	transformError,
	tryCatchTE,
	usageError,
	validationError,
	verificationError,
	withExitCode,
} from "./errors.js";
export {
	altO,
	bindTE,
	chain,
	chainFirstTE,
	chainTE,
	DoTE,
	type Either,
	findFirst,
	flow,
	fold,
	foldO,
	foldTE,
	fromEither,
	fromNullable,
	fromOption,
	fromPredicate,
	fromPredicateO,
	getOrElse,
	getOrElseO,
	identity,
	isLeft,
	isNone,
	isRight,
	isSome,
	left,
	leftTE,
	map,
	mapA,
	mapLeft,
	mapO,
	mapTE,
	none,
	type Option,
	pipe,
	right,
	rightTE,
	some,
	type Task,
	type TaskEither,
	tryCatch,
} from "./fp.js";
export {
	createLogger,
	type Logger,
	type LoggerOptions,
	LogLevel,
} from "./logger.js";
export {
	getLogicalStepDisplayId,
	getLogicalStepKey,
	isNamespacedLifecycleStep,
} from "./logical-step.js";
export {
	confirmAction,
	type PromptOptions,
	selectMultiple,
	selectOption,
} from "./prompts.js";
export { detectRuntime, isBun, type RuntimeInfo } from "./runtime.js";
