import { afterAll, beforeAll, describe, expect, test } from "bun:test";
import { mkdirSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import path from "node:path";
import { executeExtract } from "../../../agent-tools/comment-extract/index.js";
import {
	captureMainRepoState,
	cleanupTempDir,
	createInitialCommit,
	createTempDir,
	expectLeft,
	expectRight,
	getErrorMessage,
	initTestRepo,
	spawnGit,
	verifyNoMainRepoContamination,
	writeFixture,
} from "../../helpers/index.js";

const getDefaultBranch = async (repoPath: string): Promise<string> => {
	const proc = spawnGit(["rev-parse", "--abbrev-ref", "HEAD"], {
		cwd: repoPath,
	});
	await proc.exited;
	return (await new Response(proc.stdout as ReadableStream).text()).trim();
};

describe("comment-extract manifest extraction", () => {
	let tempDir: string;

	beforeAll(async () => {
		tempDir = await createTempDir("comment-extract-manifest-test");
	});

	afterAll(async () => {
		await cleanupTempDir(tempDir);
	});

	test("extracts only comments inside manifest-owned lines and hunks", async () => {
		await writeFixture(
			tempDir,
			"owned.ts",
			`// outside
const a = 1;
// owned line
const b = 2;
// owned hunk
const c = 3;
`,
		);
		const manifestPath = await writeFixture(
			tempDir,
			"change-manifest-001.json",
			JSON.stringify({
				version: 1,
				files: [
					{
						path: "owned.ts",
						ownedLines: [3],
						ownedHunks: [{ startLine: 5, endLine: 6 }],
						allowedOperations: ["remove_comments"],
					},
				],
			}),
		);

		const result = await executeExtract(
			{
				scope: "manifest",
				base: "manifest",
				changeManifest: manifestPath,
				codeRoot: tempDir,
			},
			tempDir,
		)();
		const output = expectRight(result);

		expect(output.data.scope).toBe("manifest");
		expect(output.data.filesScanned).toBe(1);
		expect(output.data.linesAdded).toBe(3);
		expect(output.data.comments.map((comment) => comment.line)).toEqual([3, 5]);
	});

	test("rejects manifest files outside CODE_ROOT", async () => {
		const manifestPath = await writeFixture(
			tempDir,
			"bad-manifest.json",
			JSON.stringify({
				version: 1,
				files: [
					{
						path: path.join(path.dirname(tempDir), "escape.ts"),
						ownedLines: [1],
					},
				],
			}),
		);

		const result = await executeExtract(
			{
				scope: "manifest",
				base: "manifest",
				changeManifest: manifestPath,
				codeRoot: tempDir,
			},
			tempDir,
		)();
		const error = expectLeft(result);

		expect(getErrorMessage(error)).toContain("outside CODE_ROOT");
	});
});

describe("comment-extract command behavior", () => {
	let testDir: string;
	let repoRoot: string;
	let defaultBranch: string;
	let mainRepoSnapshot: Awaited<ReturnType<typeof captureMainRepoState>>;

	beforeAll(async () => {
		mainRepoSnapshot = await captureMainRepoState();
		testDir = path.join(tmpdir(), `comment-extract-command-test-${Date.now()}`);
		repoRoot = path.join(testDir, "repo");

		mkdirSync(repoRoot, { recursive: true });
		await initTestRepo(repoRoot);
		await createInitialCommit(repoRoot);
		defaultBranch = await getDefaultBranch(repoRoot);

		const checkout = spawnGit(["checkout", "-b", "generated-comments"], {
			cwd: repoRoot,
		});
		await checkout.exited;

		mkdirSync(path.join(repoRoot, "catalog"), { recursive: true });
		mkdirSync(path.join(repoRoot, "cli/src/init/templates"), {
			recursive: true,
		});
		mkdirSync(path.join(repoRoot, "src"), { recursive: true });

		await Bun.write(
			path.join(repoRoot, "catalog/agents.yaml"),
			`# rp1 Agents Catalogue
# Auto-generated by the registry-backed catalog maintenance flow.
agents: []
`,
		);
		await Bun.write(
			path.join(repoRoot, "cli/src/init/templates/generated.ts"),
			`// AUTO-GENERATED FILE - DO NOT EDIT
export const AGENTS_TEMPLATE = "";
`,
		);
		await Bun.write(
			path.join(repoRoot, "src/regular.ts"),
			`// regular comment
export const value = 1;
`,
		);

		const add = spawnGit(["add", "."], { cwd: repoRoot });
		await add.exited;
		const commit = spawnGit(["commit", "-m", "Add generated outputs"], {
			cwd: repoRoot,
		});
		await commit.exited;
	});

	afterAll(async () => {
		if (testDir) {
			rmSync(testDir, { recursive: true, force: true });
		}
		await verifyNoMainRepoContamination(mainRepoSnapshot);
	});

	test("skips required generated headers in branch extraction", async () => {
		const result = await executeExtract(
			{ scope: "branch", base: defaultBranch },
			repoRoot,
		)();
		const output = expectRight(result);
		const filesWithComments = output.data.comments.map(
			(comment) => comment.file,
		);

		expect(output.success).toBe(true);
		expect(filesWithComments).toContain("src/regular.ts");
		expect(filesWithComments).not.toContain("catalog/agents.yaml");
		expect(filesWithComments).not.toContain(
			"cli/src/init/templates/generated.ts",
		);
	});
});
