name: Documentation Improvement
description: Suggest an improvement to the documentation
title: "[Docs] "
labels: ["documentation"]
body:
  - type: input
    id: page
    attributes:
      label: Page URL
      description: Which page needs improvement?
      placeholder: "https://rp1.run/..."
    validations:
      required: true
  - type: textarea
    id: current
    attributes:
      label: Current Content
      description: What does it currently say?
    validations:
      required: false
  - type: textarea
    id: suggested
    attributes:
      label: Suggested Change
      description: What should it say instead?
    validations:
      required: true
  - type: textarea
    id: rationale
    attributes:
      label: Rationale
      description: Why is this change needed?
    validations:
      required: false
