/**
 * Hidden CLI command for simulating workflow runs.
 *
 * Emits real events into the rp1 event pipeline without executing agents,
 * enabling rapid, repeatable UI testing of the Web UI dashboard.
 */

import { dirname } from "node:path";
import chalk from "chalk";
import { Command } from "commander";
import * as E from "fp-ts/lib/Either.js";
import { executeEmit } from "../agent-tools/emit/index.js";
import type { EmitInput } from "../agent-tools/emit/models.js";
import { resolveRp1Root } from "../agent-tools/rp1-root-dir/resolver.js";
import {
	deriveOrderedSteps,
	loadStateMachine,
	type OrderedStep,
} from "../agent-tools/state-machine/index.js";

type Speed = "fast" | "normal" | "slow";

interface FakeOptions {
	readonly speed: Speed;
	readonly feature?: string;
	readonly failAt?: string;
	readonly pauseAt?: string;
	readonly withBtw: boolean;
	readonly withArtifacts: boolean;
	readonly withSubflows: boolean;
	readonly count: number;
}

/** Parse the command string to extract the workflow name. */
export const parseWorkflowName = (commandStr: string): string => {
	const trimmed = commandStr.trim().replace(/^\/+/, "");
	const firstToken = trimmed.split(/\s+/)[0];
	return firstToken;
};

/** Generate a feature ID from the --feature option or a timestamp. */
export const generateFeatureId = (featureOption?: string): string => {
	if (featureOption) return featureOption;
	return `fake-${Date.now()}`;
};

/** Generate a fake-prefixed run ID. */
export const generateRunId = (): string => {
	return `fake-${crypto.randomUUID()}`;
};

/** Get the delay range for a given speed setting. */
const getDelayMs = (speed: Speed): number => {
	switch (speed) {
		case "fast":
			return 500;
		case "normal":
			return 2000 + Math.random() * 3000;
		case "slow":
			return 5000 + Math.random() * 10000;
	}
};

/** Static mapping of step IDs to contextual BTW messages. */
const BTW_MESSAGES: Record<string, readonly string[]> = {
	requirements: [
		"Analyzing project context...",
		"Gathering requirements from stakeholders...",
	],
	design: [
		"Evaluating architecture patterns...",
		"Generating design document...",
	],
	tasks: [
		"Breaking down implementation into tasks...",
		"Prioritizing task dependencies...",
	],
	build: ["Implementing component...", "Writing unit tests..."],
	verify: ["Running verification checks...", "Reviewing code quality..."],
	archive: [
		"Archiving feature artifacts...",
		"Updating project documentation...",
	],
};

/** Static mapping of steps that produce subflows with simulated tasks. */
const SUBFLOW_STEPS: Record<
	string,
	{
		readonly name: string;
		readonly tasks: readonly string[];
	}
> = {
	build: {
		name: "build-tasks",
		tasks: ["T-001", "T-002", "T-003"],
	},
	verify: {
		name: "verify-checks",
		tasks: ["T-001", "T-002"],
	},
};

/** Generate a mermaid stateDiagram-v2 for a subflow's tasks. */
const generateSubflowDiagram = (tasks: readonly string[]): string => {
	const lines = ["stateDiagram-v2"];
	if (tasks.length === 0) return lines.join("\n");

	lines.push(`    [*] --> ${tasks[0]}`);
	for (let i = 0; i < tasks.length - 1; i++) {
		lines.push(`    ${tasks[i]} --> ${tasks[i + 1]}`);
	}
	lines.push(`    ${tasks[tasks.length - 1]} --> [*]`);
	return lines.join("\n");
};

/** Static mapping of steps that produce artifacts. */
const ARTIFACT_STEPS: Record<
	string,
	{ readonly path: string; readonly content: string }
> = {
	requirements: {
		path: "requirements.md",
		content:
			"# Fake Requirements Artifact\n\nGenerated by rp1 fake for UI testing.\n",
	},
	design: {
		path: "design.md",
		content:
			"# Fake Design Artifact\n\nGenerated by rp1 fake for UI testing.\n",
	},
	tasks: {
		path: "tasks.md",
		content: "# Fake Tasks Artifact\n\nGenerated by rp1 fake for UI testing.\n",
	},
};

/** Resolve the project path using resolveRp1Root with cwd fallback. */
const resolveProjectPath = async (): Promise<string> => {
	const result = await resolveRp1Root()();
	if (E.isRight(result)) {
		return dirname(result.right.root);
	}
	return process.cwd();
};

/** Validate that a step name exists in the ordered steps list. */
const validateStepName = (
	stepName: string,
	orderedSteps: readonly OrderedStep[],
	optionName: string,
): void => {
	const validStepIds = orderedSteps.map((s) => s.id);
	if (!validStepIds.includes(stepName)) {
		console.error(
			chalk.red(
				`Error: Invalid step '${stepName}' for ${optionName}. Valid steps: ${validStepIds.join(", ")}`,
			),
		);
		process.exit(1);
	}
};

/** Emit a status_change event via executeEmit. */
const emitStatusChange = async (params: {
	runId: string;
	step?: string;
	unit?: string;
	status: string;
	workflow: string;
	feature: string;
	projectPath: string;
	closeRun?: boolean;
}): Promise<void> => {
	const input: EmitInput = {
		type: "status_change",
		runId: params.runId,
		step: params.step,
		unit: params.unit,
		data: {
			status: params.status,
			workflow: params.workflow,
			feature: params.feature,
		},
		projectPath: params.projectPath,
		closeRun: params.closeRun,
	};

	const result = await executeEmit(input)();
	if (E.isLeft(result)) {
		console.error(
			chalk.yellow(
				`Warning: Failed to emit event: ${JSON.stringify(result.left)}`,
			),
		);
	}
};

/** Emit a btw_update event. */
const emitBtwUpdate = async (params: {
	runId: string;
	step: string;
	message: string;
	workflow: string;
	feature: string;
	projectPath: string;
}): Promise<void> => {
	const input: EmitInput = {
		type: "btw_update",
		runId: params.runId,
		step: params.step,
		data: {
			message: params.message,
			workflow: params.workflow,
			feature: params.feature,
		},
		projectPath: params.projectPath,
	};

	await executeEmit(input)();
};

/** Emit an artifact_registered event. */
const emitArtifactRegistered = async (params: {
	runId: string;
	step: string;
	path: string;
	feature: string;
	workflow: string;
	projectPath: string;
}): Promise<void> => {
	const input: EmitInput = {
		type: "artifact_registered",
		runId: params.runId,
		step: params.step,
		data: {
			path: params.path,
			feature: params.feature,
			workflow: params.workflow,
		},
		projectPath: params.projectPath,
	};

	await executeEmit(input)();
};

/** Emit a subflow_registered event. */
const emitSubflowRegistered = async (params: {
	runId: string;
	step: string;
	parentStepId: string;
	subflowName: string;
	diagram: string;
	workflow: string;
	feature: string;
	projectPath: string;
}): Promise<void> => {
	const input: EmitInput = {
		type: "subflow_registered",
		runId: params.runId,
		step: params.step,
		data: {
			parentStepId: params.parentStepId,
			subflowName: params.subflowName,
			diagram: params.diagram,
			workflow: params.workflow,
			feature: params.feature,
		},
		projectPath: params.projectPath,
	};

	await executeEmit(input)();
};

const sleep = (ms: number): Promise<void> =>
	new Promise((resolve) => setTimeout(resolve, ms));

/** Run a single simulated workflow. */
const simulateRun = async (
	runIndex: number,
	totalRuns: number,
	workflowName: string,
	orderedSteps: readonly OrderedStep[],
	options: FakeOptions,
	projectPath: string,
): Promise<void> => {
	const runId = generateRunId();
	const featureId = generateFeatureId(options.feature);
	const prefix = totalRuns > 1 ? `[Run ${runIndex}/${totalRuns}] ` : "";
	const stepCount = orderedSteps.length;

	console.log(
		`${prefix}${chalk.cyan("rp1 fake")}: Simulating workflow "${workflowName}" (${stepCount} steps, speed: ${options.speed})`,
	);
	console.log(`${prefix}  Run ID: ${runId}`);
	console.log(`${prefix}  Feature: ${featureId}`);
	console.log();

	const startTime = Date.now();

	for (let i = 0; i < orderedSteps.length; i++) {
		const step = orderedSteps[i];
		const stepLabel = `[${i + 1}/${stepCount}] ${step.id}`;

		console.log(`${prefix}  ${stepLabel}: ${chalk.yellow("running")}...`);
		await emitStatusChange({
			runId,
			step: step.id,
			status: "running",
			workflow: workflowName,
			feature: featureId,
			projectPath,
		});

		if (options.withBtw) {
			const messages = BTW_MESSAGES[step.id] ?? [
				"Processing step...",
				`Working on ${step.label}...`,
			];
			for (const message of messages.slice(0, 2)) {
				await sleep(getDelayMs(options.speed) / 4);
				await emitBtwUpdate({
					runId,
					step: step.id,
					message,
					workflow: workflowName,
					feature: featureId,
					projectPath,
				});
			}
		}

		await sleep(getDelayMs(options.speed));

		if (options.failAt === step.id) {
			console.log(`${prefix}  ${stepLabel}: ${chalk.red("failed")} (injected)`);
			await emitStatusChange({
				runId,
				step: step.id,
				status: "failed",
				workflow: workflowName,
				feature: featureId,
				projectPath,
			});
			await emitStatusChange({
				runId,
				status: "failed",
				workflow: workflowName,
				feature: featureId,
				projectPath,
				closeRun: true,
			});
			const elapsed = ((Date.now() - startTime) / 1000).toFixed(1);
			console.log(
				`\n${prefix}${chalk.red("Simulation failed")} at step "${step.id}". Total time: ${elapsed}s`,
			);
			return;
		}

		if (options.pauseAt === step.id) {
			console.log(
				`${prefix}  ${stepLabel}: ${chalk.yellow("waiting")} (injected)`,
			);
			await emitStatusChange({
				runId,
				step: step.id,
				status: "waiting",
				workflow: workflowName,
				feature: featureId,
				projectPath,
			});
			const elapsed = ((Date.now() - startTime) / 1000).toFixed(1);
			console.log(
				`\n${prefix}${chalk.yellow("Simulation paused")} at step "${step.id}". Total time: ${elapsed}s`,
			);
			return;
		}

		const stepElapsed = ((Date.now() - startTime) / 1000).toFixed(1);
		console.log(
			`${prefix}  ${stepLabel}: ${chalk.green("completed")} (${stepElapsed}s)`,
		);
		await emitStatusChange({
			runId,
			step: step.id,
			status: "completed",
			workflow: workflowName,
			feature: featureId,
			projectPath,
		});

		if (options.withArtifacts && ARTIFACT_STEPS[step.id]) {
			const artifact = ARTIFACT_STEPS[step.id];
			const artifactPath = `work/features/${featureId}/${artifact.path}`;
			const fullDir = `${projectPath}/.rp1/work/features/${featureId}`;

			try {
				const { mkdir, writeFile } = await import("node:fs/promises");
				await mkdir(fullDir, { recursive: true });
				await writeFile(`${fullDir}/${artifact.path}`, artifact.content);
			} catch {
				// Best-effort file creation
			}

			await emitArtifactRegistered({
				runId,
				step: step.id,
				path: artifactPath,
				feature: featureId,
				workflow: workflowName,
				projectPath,
			});
		}

		if (options.withSubflows && SUBFLOW_STEPS[step.id]) {
			const subflow = SUBFLOW_STEPS[step.id];
			const diagram = generateSubflowDiagram(subflow.tasks);

			await emitSubflowRegistered({
				runId,
				step: step.id,
				parentStepId: step.id,
				subflowName: subflow.name,
				diagram,
				workflow: workflowName,
				feature: featureId,
				projectPath,
			});

			for (const taskId of subflow.tasks) {
				await emitStatusChange({
					runId,
					step: step.id,
					unit: taskId,
					status: "running",
					workflow: workflowName,
					feature: featureId,
					projectPath,
				});
				await sleep(getDelayMs(options.speed) / 3);
				await emitStatusChange({
					runId,
					step: step.id,
					unit: taskId,
					status: "completed",
					workflow: workflowName,
					feature: featureId,
					projectPath,
				});
			}
		}
	}

	await emitStatusChange({
		runId,
		status: "completed",
		workflow: workflowName,
		feature: featureId,
		projectPath,
		closeRun: true,
	});

	const totalElapsed = ((Date.now() - startTime) / 1000).toFixed(1);
	console.log(
		`\n${prefix}${chalk.green("Simulation complete")}. Total time: ${totalElapsed}s`,
	);
};

export const fakeCommand = new Command("fake")
	.description("Simulate workflow runs for UI testing (developer tool)")
	.argument("<command>", "Workflow command string (e.g., \"/build 'test'\")")
	.option(
		"-s, --speed <speed>",
		"Simulation speed: fast, normal, slow",
		"normal",
	)
	.option("-f, --feature <id>", "Feature ID (auto-generated if omitted)")
	.option("--fail-at <step>", "Inject failure at specified step")
	.option("--pause-at <step>", "Inject pause/waiting state at specified step")
	.option("--with-btw", "Emit BTW update messages during steps", false)
	.option(
		"--with-artifacts",
		"Create fake artifact files and emit events",
		false,
	)
	.option("--with-subflows", "Emit subflow and unit-level events", false)
	.option("-n, --count <n>", "Number of concurrent simulated runs", "1")
	.addHelpText(
		"after",
		`
Examples:
  rp1 fake "/build 'test feature'"                      Basic simulation
  rp1 fake "/build 'test'" --speed fast                  Fast mode (~3-6s total)
  rp1 fake "/build 'test'" --fail-at build               Fail at build step
  rp1 fake "/build 'test'" --pause-at design             Pause at design step
  rp1 fake "/build 'test'" --with-btw --with-artifacts   Full simulation
  rp1 fake "/build 'test'" --with-subflows               Include sub-flows
  rp1 fake "/build 'test'" --count 5 --speed fast        5 concurrent runs
  rp1 fake "/build 'test'" --feature my-feature          Custom feature ID
`,
	)
	.action(async (commandStr: string, rawOptions: Record<string, unknown>) => {
		const options: FakeOptions = {
			speed: (rawOptions.speed as Speed) ?? "normal",
			feature: rawOptions.feature as string | undefined,
			failAt: rawOptions.failAt as string | undefined,
			pauseAt: rawOptions.pauseAt as string | undefined,
			withBtw: (rawOptions.withBtw as boolean) ?? false,
			withArtifacts: (rawOptions.withArtifacts as boolean) ?? false,
			withSubflows: (rawOptions.withSubflows as boolean) ?? false,
			count: Number.parseInt(rawOptions.count as string, 10) || 1,
		};

		if (!["fast", "normal", "slow"].includes(options.speed)) {
			console.error(
				chalk.red(
					`Error: Invalid speed '${options.speed}'. Must be one of: fast, normal, slow`,
				),
			);
			process.exit(1);
		}

		const workflowName = parseWorkflowName(commandStr);
		if (!workflowName) {
			console.error(
				chalk.red(
					"Error: Could not extract workflow name from command string.",
				),
			);
			process.exit(1);
		}

		const machineResult = await loadStateMachine(workflowName)();
		if (E.isLeft(machineResult)) {
			console.error(
				chalk.red(
					`Error: No state machine found for workflow '${workflowName}'.`,
				),
			);
			console.error(
				`Ensure a ## STATE-MACHINE section with a stateDiagram-v2 block exists in the skill or agent markdown file.`,
			);
			process.exit(1);
		}

		const machine = machineResult.right;

		const orderedSteps = deriveOrderedSteps(machine);
		if (orderedSteps.length === 0) {
			console.error(
				chalk.red(`Error: State machine for '${workflowName}' has no steps.`),
			);
			process.exit(1);
		}

		if (options.failAt) {
			validateStepName(options.failAt, orderedSteps, "--fail-at");
		}
		if (options.pauseAt) {
			validateStepName(options.pauseAt, orderedSteps, "--pause-at");
		}

		const projectPath = await resolveProjectPath();

		if (options.count > 1) {
			const promises: Promise<void>[] = [];
			for (let i = 0; i < options.count; i++) {
				const stagger = Math.random() * 400 + 100;
				promises.push(
					sleep(stagger).then(() =>
						simulateRun(
							i + 1,
							options.count,
							workflowName,
							orderedSteps,
							options,
							projectPath,
						),
					),
				);
			}
			await Promise.allSettled(promises);
		} else {
			await simulateRun(1, 1, workflowName, orderedSteps, options, projectPath);
		}
	});
