// AUTO-GENERATED FILE - DO NOT EDIT
// Generated by: bun run scripts/generate-asset-imports.ts
// Source: src/build/templates/init/instruction-file.liquid

export const CLAUDE_CODE_TEMPLATE =
	"## rp1 Knowledge Base\n\n**Use Progressive Disclosure Pattern**\n\nLocation: `.rp1/context/`\n\nFiles:\n- index.md (always load first)\n- architecture.md\n- modules.md\n- patterns.md\n- concept_map.md\n\nLoading rules:\n1. Always read index.md first.\n2. Then load based on task type:\n   - Code review: patterns.md\n   - Bug investigation: architecture.md, modules.md\n   - Feature work: modules.md, patterns.md\n   - Strategic or system-wide analysis: all files";

export const AGENTS_TEMPLATE =
	"## rp1 Knowledge Base\n\n**Use Progressive Disclosure Pattern**\n\nLocation: `.rp1/context/`\n\nFiles:\n- index.md (always load first)\n- architecture.md\n- modules.md\n- patterns.md\n- concept_map.md\n\nLoading rules:\n1. Always read index.md first.\n2. Then load based on task type:\n   - Code review: patterns.md\n   - Bug investigation: architecture.md, modules.md\n   - Feature work: modules.md, patterns.md\n   - Strategic or system-wide analysis: all files";

export const CODEX_TEMPLATE =
	"## rp1 Knowledge Base\n\n**Use Progressive Disclosure Pattern**\n\nLocation: `.rp1/context/`\n\nFiles:\n- index.md (always load first)\n- architecture.md\n- modules.md\n- patterns.md\n- concept_map.md\n\nLoading rules:\n1. Always read index.md first.\n2. Then load based on task type:\n   - Code review: patterns.md\n   - Bug investigation: architecture.md, modules.md\n   - Feature work: modules.md, patterns.md\n   - Strategic or system-wide analysis: all files\n\n## Codex agent conventions\n\n**Task shorthand**: `Task: <sub-agent-name>` means spawn that sub-agent. Treat it as an execution directive, not descriptive text.\n\n**Subagent waiting**: Do not assume a subagent failed because it is slow. Wait for completion before declaring it stalled. Check for expected side effects (artifact files, DB writes) before concluding it is stuck. Prefer patient polling over short timeouts for critical-path subagents.";
