import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { Liquid } from "liquidjs";

const INIT_TEMPLATE_PLATFORMS = ["claude-code", "opencode", "codex"] as const;

type InitTemplatePlatform = (typeof INIT_TEMPLATE_PLATFORMS)[number];

export const INIT_TEMPLATE_SOURCE_RELATIVE_PATH = join(
	"cli",
	"src",
	"build",
	"templates",
	"init",
	"instruction-file.liquid",
);

export const INIT_TEMPLATE_OUTPUT_RELATIVE_PATH = join(
	"cli",
	"src",
	"init",
	"templates",
	"generated.ts",
);

export const readInitInstructionTemplate = async (
	projectRoot: string,
): Promise<string> =>
	readFile(join(projectRoot, INIT_TEMPLATE_SOURCE_RELATIVE_PATH), "utf-8");

const renderGeneratedInstructionModule = (
	rendered: Readonly<Record<InitTemplatePlatform, string>>,
): string => `// AUTO-GENERATED FILE - DO NOT EDIT
// Generated by: registry-backed init template generator
// Source: src/build/templates/init/instruction-file.liquid

export const CLAUDE_CODE_TEMPLATE =
	${JSON.stringify(rendered["claude-code"])};

export const AGENTS_TEMPLATE =
	${JSON.stringify(rendered.opencode)};

export const CODEX_TEMPLATE =
	${JSON.stringify(rendered.codex)};
`;

export const buildGeneratedInitTemplatesFile = async (
	templateSource: string,
	skillAwarenessBlock: string,
): Promise<string> => {
	const engine = new Liquid({
		strictVariables: true,
		strictFilters: true,
	});

	const rendered = Object.fromEntries(
		await Promise.all(
			INIT_TEMPLATE_PLATFORMS.map(async (platform) => [
				platform,
				await engine.parseAndRender(templateSource, {
					platform,
					skillAwarenessBlock,
				}),
			]),
		),
	) as Record<InitTemplatePlatform, string>;

	return renderGeneratedInstructionModule(rendered);
};

export const writeGeneratedInitTemplatesFile = async (
	projectRoot: string,
	content: string,
): Promise<void> => {
	const outputPath = join(projectRoot, INIT_TEMPLATE_OUTPUT_RELATIVE_PATH);
	await mkdir(dirname(outputPath), { recursive: true });
	await writeFile(outputPath, content);
};
