#!/usr/bin/env bash
# generate-catalog.sh — Generate catalog/skills.yaml and catalog/agents.yaml
# from plugin source files. Run via `just catalog-generate`.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
PLUGINS_DIR="$REPO_ROOT/plugins"
CATALOG_DIR="$REPO_ROOT/catalog"

# Only catalog distributable plugins (utils is internal-only)
DIST_PLUGINS=("base" "dev")

mkdir -p "$CATALOG_DIR"

# ─────────────────────────────────────────────────────────────────────────────
# Helpers
# ─────────────────────────────────────────────────────────────────────────────

# Extract a frontmatter field from a markdown file with YAML frontmatter
fm_field() {
    local file="$1" field="$2"
    sed -n '/^---$/,/^---$/p' "$file" | grep "^${field}:" | sed "s/^${field}: *//" | sed 's/^"//' | sed 's/"$//'
}

# Compute SHA-256 of a file (just the hash, no filename)
file_checksum() {
    shasum -a 256 "$1" | cut -d' ' -f1
}

# Get last modified date of a file in ISO format
file_date() {
    stat -f '%Sm' -t '%Y-%m-%d' "$1" 2>/dev/null || date -r "$1" '+%Y-%m-%d' 2>/dev/null || echo "unknown"
}

# Escape a string for YAML (wrap in quotes if it contains special chars)
yaml_str() {
    local s="$1"
    if echo "$s" | grep -qE '[:{}\[\],&*?|>!%@`#'"'"']'; then
        echo "\"$(echo "$s" | sed 's/"/\\"/g')\""
    else
        echo "$s"
    fi
}

# Get plugin name from path (base/dev/utils)
plugin_name() {
    local path="$1"
    echo "$path" | sed "s|${PLUGINS_DIR}/||" | cut -d/ -f1
}

# ─────────────────────────────────────────────────────────────────────────────
# Scan: collect all skill and agent names first (for cross-reference lookup)
# ─────────────────────────────────────────────────────────────────────────────

declare -a ALL_SKILL_IDS=()
declare -a ALL_SKILL_FILES=()
declare -a ALL_AGENT_IDS=()
declare -a ALL_AGENT_FILES=()

for plugin in "${DIST_PLUGINS[@]}"; do
    plugin_dir="$PLUGINS_DIR/$plugin"
    [ -d "$plugin_dir" ] || continue
    prefix="rp1-${plugin}"

    # Skills
    if [ -d "$plugin_dir/skills" ]; then
        for skill_dir in "$plugin_dir"/skills/*/; do
            [ -d "$skill_dir" ] || continue
            skill_file="$skill_dir/SKILL.md"
            [ -f "$skill_file" ] || continue
            skill_name=$(basename "$skill_dir")
            ALL_SKILL_IDS+=("${prefix}:${skill_name}")
            ALL_SKILL_FILES+=("$skill_file")
        done
    fi

    # Agents
    if [ -d "$plugin_dir/agents" ]; then
        for agent_file in "$plugin_dir"/agents/*.md; do
            [ -f "$agent_file" ] || continue
            agent_name=$(basename "$agent_file" .md)
            ALL_AGENT_IDS+=("${prefix}:${agent_name}")
            ALL_AGENT_FILES+=("$agent_file")
        done
    fi
done

# ─────────────────────────────────────────────────────────────────────────────
# Cross-reference: for each skill/agent, find who references it
# ─────────────────────────────────────────────────────────────────────────────

# Search all plugin files for references to a given ID
find_references() {
    local target_id="$1" target_name="$2"
    # Search all .md files in plugins/ for the target ID or bare name
    grep -rl "$target_id\|${target_name}" "$PLUGINS_DIR" --include='*.md' 2>/dev/null || true
}

# ─────────────────────────────────────────────────────────────────────────────
# Generate catalog/skills.yaml
# ─────────────────────────────────────────────────────────────────────────────

echo "Generating catalog/skills.yaml ..."

cat > "$CATALOG_DIR/skills.yaml" << 'HEADER'
# rp1 Skills Catalogue
# Auto-generated by scripts/generate-catalog.sh
# Run `just catalog-generate` to regenerate.
# Run `just catalog-check` to verify freshness.
#
# DO NOT EDIT MANUALLY — changes will be overwritten.

skills:
HEADER

for i in "${!ALL_SKILL_IDS[@]}"; do
    skill_id="${ALL_SKILL_IDS[$i]}"
    skill_file="${ALL_SKILL_FILES[$i]}"
    skill_name=$(basename "$(dirname "$skill_file")")
    plugin=$(plugin_name "$skill_file")
    prefix="rp1-${plugin}"

    description=$(fm_field "$skill_file" "description")
    [ -z "$description" ] && description=$(fm_field "$skill_file" "name")

    checksum=$(file_checksum "$skill_file")
    last_update=$(file_date "$skill_file")

    # Find agents this skill uses (referenced in its body)
    uses_agents=()
    for j in "${!ALL_AGENT_IDS[@]}"; do
        agent_id="${ALL_AGENT_IDS[$j]}"
        agent_bare=$(basename "${ALL_AGENT_FILES[$j]}" .md)
        if grep -q "$agent_id\|${prefix}:${agent_bare}\|subagent.*${agent_bare}" "$skill_file" 2>/dev/null; then
            uses_agents+=("$agent_id")
        fi
    done

    # Find skills this skill uses
    uses_skills=()
    for j in "${!ALL_SKILL_IDS[@]}"; do
        other_id="${ALL_SKILL_IDS[$j]}"
        [ "$other_id" = "$skill_id" ] && continue
        if grep -q "$other_id" "$skill_file" 2>/dev/null; then
            uses_skills+=("$other_id")
        fi
    done

    # Find skills that reference this skill
    skills_that_use_me=()
    for j in "${!ALL_SKILL_IDS[@]}"; do
        other_id="${ALL_SKILL_IDS[$j]}"
        other_file="${ALL_SKILL_FILES[$j]}"
        [ "$other_id" = "$skill_id" ] && continue
        if grep -q "$skill_id\|${prefix}:${skill_name}" "$other_file" 2>/dev/null; then
            skills_that_use_me+=("$other_id")
        fi
    done

    # Find agents that reference this skill
    agents_that_use_me=()
    for j in "${!ALL_AGENT_IDS[@]}"; do
        agent_file="${ALL_AGENT_FILES[$j]}"
        if grep -q "$skill_id\|${prefix}:${skill_name}" "$agent_file" 2>/dev/null; then
            agents_that_use_me+=("${ALL_AGENT_IDS[$j]}")
        fi
    done

    # Write YAML entry
    cat >> "$CATALOG_DIR/skills.yaml" << EOF
  - name: $skill_id
    description: $(yaml_str "${description:-$skill_name}")
    plugin: $plugin
    skills_that_use_me: [$(IFS=', '; echo "${skills_that_use_me[*]:-}")]
    agents_that_use_me: [$(IFS=', '; echo "${agents_that_use_me[*]:-}")]
    sub_agents_that_i_use: [$(IFS=', '; echo "${uses_agents[*]:-}")]
    skills_that_i_use: [$(IFS=', '; echo "${uses_skills[*]:-}")]
    last_update: "$last_update"
    last_checksum: $checksum
EOF
done

skill_count=${#ALL_SKILL_IDS[@]}
echo "  → $skill_count skills catalogued"

# ─────────────────────────────────────────────────────────────────────────────
# Generate catalog/agents.yaml
# ─────────────────────────────────────────────────────────────────────────────

echo "Generating catalog/agents.yaml ..."

cat > "$CATALOG_DIR/agents.yaml" << 'HEADER'
# rp1 Agents Catalogue
# Auto-generated by scripts/generate-catalog.sh
# Run `just catalog-generate` to regenerate.
# Run `just catalog-check` to verify freshness.
#
# DO NOT EDIT MANUALLY — changes will be overwritten.

agents:
HEADER

for i in "${!ALL_AGENT_IDS[@]}"; do
    agent_id="${ALL_AGENT_IDS[$i]}"
    agent_file="${ALL_AGENT_FILES[$i]}"
    agent_name=$(basename "$agent_file" .md)
    plugin=$(plugin_name "$agent_file")
    prefix="rp1-${plugin}"

    description=$(fm_field "$agent_file" "description")
    [ -z "$description" ] && description=$(fm_field "$agent_file" "name")

    checksum=$(file_checksum "$agent_file")
    last_update=$(file_date "$agent_file")

    # Find skills this agent uses
    uses_skills=()
    for j in "${!ALL_SKILL_IDS[@]}"; do
        other_id="${ALL_SKILL_IDS[$j]}"
        if grep -q "$other_id" "$agent_file" 2>/dev/null; then
            uses_skills+=("$other_id")
        fi
    done

    # Find skills that reference this agent
    skills_that_use_me=()
    for j in "${!ALL_SKILL_IDS[@]}"; do
        skill_file="${ALL_SKILL_FILES[$j]}"
        if grep -q "$agent_id\|${prefix}:${agent_name}" "$skill_file" 2>/dev/null; then
            skills_that_use_me+=("${ALL_SKILL_IDS[$j]}")
        fi
    done

    # Write YAML entry
    cat >> "$CATALOG_DIR/agents.yaml" << EOF
  - name: $agent_id
    description: $(yaml_str "${description:-$agent_name}")
    plugin: $plugin
    skills_that_i_use: [$(IFS=', '; echo "${uses_skills[*]:-}")]
    skills_that_use_me: [$(IFS=', '; echo "${skills_that_use_me[*]:-}")]
    last_update: "$last_update"
    last_checksum: $checksum
EOF
done

agent_count=${#ALL_AGENT_IDS[@]}
echo "  → $agent_count agents catalogued"
echo ""
echo "Catalogue generated: catalog/skills.yaml, catalog/agents.yaml"
