import { latte, frappe, macchiato, mocha } from '../src/flavors';
import type { FlavorExport } from '../src/types';

const cssDir = `${import.meta.dirname}/../dist/css`;

function generateFlavorCSS(flavor: FlavorExport): string {
  const lines: string[] = [];

  lines.push(`/* Catppuccin ${flavor.name} Theme for Mermaid */`);
  lines.push(`/* Generated by @rp1/catppuccin-mermaid */`);
  lines.push('');
  lines.push(':root {');

  for (const [colorName, hexValue] of Object.entries(flavor.colors)) {
    lines.push(`  --ctp-${colorName}: ${hexValue};`);
  }

  lines.push('}');

  return lines.join('\n');
}

async function generateAllFlavorsCSS(): Promise<void> {
  await Bun.$`mkdir -p ${cssDir}`;

  const flavors: FlavorExport[] = [latte, frappe, macchiato, mocha];

  for (const flavor of flavors) {
    const css = generateFlavorCSS(flavor);
    const filename = `${flavor.id}.css`;
    const filepath = `${cssDir}/${filename}`;

    await Bun.write(filepath, css);

    const file = Bun.file(filepath);
    console.log(`Generated ${filename} (${file.size} bytes)`);
  }
}

await generateAllFlavorsCSS();
console.log('\nCSS files generated successfully');
