import { latte, mocha } from '../src/flavors';

const mkdocsDir = `${import.meta.dirname}/../dist/mkdocs`;

function generateMkDocsCSS(): string {
  const lines: string[] = [];

  lines.push('/* Catppuccin Theme for Mermaid - MkDocs Material Integration */');
  lines.push('/* Generated by @rp1/catppuccin-mermaid */');
  lines.push('/* Light mode: Latte, Dark mode: Mocha (per DD-005) */');
  lines.push('');

  lines.push('/* Light Mode - Catppuccin Latte */');
  lines.push('[data-md-color-scheme="default"] {');
  for (const [colorName, hexValue] of Object.entries(latte.colors)) {
    lines.push(`  --ctp-${colorName}: ${hexValue};`);
  }
  lines.push('}');
  lines.push('');

  lines.push('/* Dark Mode - Catppuccin Mocha */');
  lines.push('[data-md-color-scheme="slate"] {');
  for (const [colorName, hexValue] of Object.entries(mocha.colors)) {
    lines.push(`  --ctp-${colorName}: ${hexValue};`);
  }
  lines.push('}');

  return lines.join('\n');
}

function generateMkDocsJS(): string {
  const latteVars = JSON.stringify(latte.themeVariables, null, 2);
  const mochaVars = JSON.stringify(mocha.themeVariables, null, 2);

  return `/**
 * Catppuccin Theme for Mermaid - MkDocs Material Integration
 * Generated by @rp1/catppuccin-mermaid
 *
 * Features:
 * - Auto-detects MkDocs Material color scheme
 * - Switches theme when user toggles light/dark mode
 * - Stores original diagram code for re-rendering (DD-008)
 * - Uses MutationObserver for decoupled theme detection (DD-004)
 */
(function() {
  'use strict';

  var themes = {
    default: ${latteVars},
    slate: ${mochaVars}
  };

  function getCurrentScheme() {
    return document.documentElement.getAttribute('data-md-color-scheme') || 'default';
  }

  function getThemeVariables() {
    var scheme = getCurrentScheme();
    return themes[scheme] || themes.default;
  }

  function storeOriginalCode() {
    document.querySelectorAll('.mermaid').forEach(function(el) {
      if (!el.dataset.originalCode && el.textContent.trim()) {
        el.dataset.originalCode = el.textContent;
      }
    });
  }

  async function applyTheme() {
    if (typeof mermaid === 'undefined') {
      console.warn('[catppuccin-mermaid] Mermaid not loaded');
      return;
    }

    var themeVars = getThemeVariables();

    mermaid.initialize({
      startOnLoad: false,
      theme: 'base',
      themeVariables: themeVars
    });

    var diagrams = document.querySelectorAll('.mermaid');
    for (var i = 0; i < diagrams.length; i++) {
      var el = diagrams[i];
      var code = el.dataset.originalCode;
      if (code) {
        el.removeAttribute('data-processed');
        el.innerHTML = code;
      }
    }

    await mermaid.run();
  }

  function init() {
    storeOriginalCode();

    if (typeof mermaid !== 'undefined') {
      mermaid.initialize({
        startOnLoad: true,
        theme: 'base',
        themeVariables: getThemeVariables()
      });
    }

    var observer = new MutationObserver(function(mutations) {
      mutations.forEach(function(mutation) {
        if (mutation.attributeName === 'data-md-color-scheme') {
          applyTheme();
        }
      });
    });

    observer.observe(document.documentElement, {
      attributes: true,
      attributeFilter: ['data-md-color-scheme']
    });
  }

  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', init);
  } else {
    init();
  }
})();
`;
}

async function generateMkDocsFiles(): Promise<void> {
  await Bun.$`mkdir -p ${mkdocsDir}`;

  const css = generateMkDocsCSS();
  const cssPath = `${mkdocsDir}/catppuccin-mermaid.css`;
  await Bun.write(cssPath, css);
  console.log(`Generated catppuccin-mermaid.css (${Bun.file(cssPath).size} bytes)`);

  const js = generateMkDocsJS();
  const jsPath = `${mkdocsDir}/catppuccin-mermaid.js`;
  await Bun.write(jsPath, js);
  console.log(`Generated catppuccin-mermaid.js (${Bun.file(jsPath).size} bytes)`);
}

await generateMkDocsFiles();
console.log('\nMkDocs integration files generated successfully');
