/**
 * Type-safe data models for OpenCode installation.
 */

/**
 * Plugin manifest data from manifest.json.
 * Generated by build command, consumed by install command.
 */
export interface PluginManifest {
	readonly plugin: string;
	readonly version: string;
	readonly generatedAt: string;
	readonly opencodeVersionTested: string;
	readonly commands: readonly string[];
	readonly agents: readonly string[];
	readonly skills: readonly string[];
}

/**
 * Compute total artifacts in a manifest.
 */
export const getTotalArtifacts = (manifest: PluginManifest): number =>
	manifest.commands.length + manifest.agents.length + manifest.skills.length;

/**
 * Report of installation verification results.
 */
export interface VerificationReport {
	readonly commandsFound: number;
	readonly commandsExpected: number;
	readonly agentsFound: number;
	readonly agentsExpected: number;
	readonly skillsFound: number;
	readonly skillsExpected: number;
	readonly pluginsFound: number;
	readonly pluginsExpected: number;
	readonly issues: readonly string[];
}

/**
 * Check if installation is healthy.
 * Installation is healthy if we have at least the expected number of components.
 * Skills and plugins are optional enhancements, so missing skills/plugins
 * don't make installation unhealthy.
 */
export const isHealthy = (report: VerificationReport): boolean => {
	const criticalIssues = report.issues.filter(
		(i) =>
			!i.toLowerCase().includes("skills") &&
			!i.toLowerCase().includes("plugin"),
	);
	return (
		criticalIssues.length === 0 &&
		report.commandsFound >= report.commandsExpected &&
		report.agentsFound >= report.agentsExpected
	);
};

/**
 * Install configuration options.
 */
export interface InstallConfig {
	readonly artifactsDir: string;
	readonly skipSkills: boolean;
	readonly dryRun: boolean;
}

/**
 * Default install configuration.
 */
export const defaultInstallConfig: InstallConfig = {
	artifactsDir: "dist/opencode",
	skipSkills: false,
	dryRun: false,
};

/**
 * Prerequisite check result.
 */
export interface PrerequisiteResult {
	readonly check: string;
	readonly passed: boolean;
	readonly message: string;
	readonly value?: string;
}

/**
 * Backup manifest tracking backed up files.
 */
export interface BackupManifest {
	readonly timestamp: string;
	readonly backupPath: string;
	readonly filesBackedUp: number;
}

/**
 * Installation result summary.
 */
export interface InstallResult {
	readonly pluginsInstalled: readonly string[];
	readonly filesInstalled: number;
	readonly backupPath: string | null;
	readonly warnings: readonly string[];
}
